services:
  app:
    build:
      context: .
      args:
        VITE_MAPBOX_ACCESS_TOKEN: ${VITE_MAPBOX_ACCESS_TOKEN}
    env_file: .env
    restart: unless-stopped
    volumes:
      - ./attached_assets:/app/attached_assets:ro
    networks:
      - showpls-net

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/conf:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot
    depends_on:
      - app
    networks:
      - showpls-net

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - ./certbot/log:/var/log/letsencrypt
    entrypoint: sh -c "trap exit TERM; while :; do sleep 6h & wait $${!}; certbot renew; done"

networks:
  showpls-net:
    driver: bridge
