services:
  app:
    build: .
    environment:
      NODE_ENV: production # Lie about the environment
    ports:
      - "5000:5000"
    restart: unless-stopped

  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - app