version: "3.9"
services:
  app:
    build: .
    env_file: .env
    restart: unless-stopped
    volumes:
      - ./dist:/app/dist:ro
      - ./attached_assets:/app/attached_assets:ro
    networks:
      - showpls-net

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./dist/public:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/conf:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot:ro
    depends_on:
      - app
    networks:
      - showpls-net

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

networks:
  showpls-net:
    driver: bridge
