version: "3.9"

services:
  app:
    build: .
    env_file:
      - ./.env
    ports:
      - "5000:5000"
    restart: unless-stopped

  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
    restart: unless-stopped
