version: "3.9"
services:
  app:
    build: .
    env_file: .env
    restart: unless-stopped
    networks:
      - showpls-net

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80" # Only HTTP for now
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    networks:
      - showpls-net

networks:
  showpls-net:
    driver: bridge
